
-load $(XTRA_OUTPUTDIR)/mul$(XTRA_EXT)

$(XTRA_OUTPUTDIR)/mul$(XTRA_EXT): $(XTRA_OUTPUTDIR)/mul.o
	gcc -shared -o $@ $^  

$(XTRA_OUTPUTDIR)/mul.o: $(XTRA_SOURCE)/mul.c
	gcc $(XTRA_CFLAGS) -c $^ -o $@ -I $(XTRA_MAKEHEADERS)

XTRA_CLEANTARGETS:=$(XTRA_CLEANTARGETS) \
    $(XTRA_XTRA_OUTPUTDIR)/mul$(XTRA_EXT) $(XTRA_XTRA_OUTPUTDIR)/mul.o \


